# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'carsport' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

 platform :ios, '9.0'
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

    # Pods for myapp
    pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
    pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
    pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
    pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
    pod 'React', :path => '../node_modules/react-native/'
    pod 'React-Core', :path => '../node_modules/react-native/'
    pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
    pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
    pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
    pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
    pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
    pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
    pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
    pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
    pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
    pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
    pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
    pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
    
    pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

    pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
    pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
    pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
    pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
    pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
    pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
    pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 
 
    # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Unomment this line if you want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Uncomment this line if you want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Uncomment this line if you want to support GoogleMaps on iOS
 
  pod 'GoogleSignIn', '~> 5.0.2'
  #FaceBook login

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  # pod 'FacebookSDK'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  pod 'Google-Mobile-Ads-SDK'
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'
 

  pod 'Firebase/Core'
 
      pod 'Firebase/Messaging'
      pod 'FirebaseAnalytics'

      pod 'Google-Mobile-Ads-SDK'
  
  pod 'GoogleIDFASupport', '~> 3.14.0'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'



  # pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'


  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'RNIap', :path => '../node_modules/react-native-iap'
  pod 'Bolts'
  pod 'react-native-admob', :path => '../node_modules/react-native-admob'


  # pod 'Firebase/Auth'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
 
  pod 'Firebase/Auth','~> 6.17.0'


  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'
  source 'https://cdn.cocoapods.org/'

  pod 'RCTRestart', :path => '../node_modules/react-native-restart/ios'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'
  
 
  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-background-upload', :path => '../node_modules/react-native-background-upload'

  pod 'GPUImage', git: 'https://github.com/BunHouth/GPUImage.git'

  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'

  pod 'RNFS', :path => '../node_modules/react-native-fs'


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'rn-media-meta', :path => '../node_modules/rn-media-meta'
  pod 'RNVideoProcessing', :path => '../node_modules/react-native-video-processing'

end

post_install do |installer|
 ## Fix for XCode 12.5
      find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
      "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
      find_and_replace("../node_modules/react-native/ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm",
      "RCTBridgeModuleNameForClass(module))", "RCTBridgeModuleNameForClass(Class(module)))")
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end
